name:                component1

dependencies:
- base >= 4.7 && < 5
- file-embed

library:
  source-dirs: src

executables:
  component1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - component1

tests:
  component1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - component1
